import { describe, expect, it } from "vitest";
import { renderMarkdownDocumentHtml } from "../src/manual-test-verification-presentation.js";

describe("design artifact print presentation", () => {
  it("renders escaped Markdown with an explicit Hepha footer and no browser metadata", () => {
    const html = renderMarkdownDocumentHtml("# Design <script>\n\n| A | B |\n| --- | --- |\n| 1 | 2 |", "Generated by Hepha Design Feature");

    expect(html).toContain("<h1>Design &lt;script&gt;</h1>");
    expect(html).toContain("Generated by Hepha Design Feature");
    expect(html).toContain("<table>");
    expect(html).not.toContain("file://");
  });
});
