import { renderMarkdownDocumentHtml } from "../manual-test-verification-presentation.js";

const PDF_RENDER_TIMEOUT_MS = 30_000;

export interface DesignArtifactPdf {
  readonly bytes: Buffer;
  readonly fileName: string;
}

/** Renders one local Design Feature Markdown artifact into an in-memory PDF. */
export async function renderDesignArtifactPdf(
  markdown: string,
  markdownFileName: string,
): Promise<DesignArtifactPdf> {
  const { chromium } = await import("@playwright/test");
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(
      renderMarkdownDocumentHtml(markdown, "Generated by Hepha Design Feature"),
      { timeout: PDF_RENDER_TIMEOUT_MS, waitUntil: "networkidle" },
    );
    const bytes = await page.pdf({
      displayHeaderFooter: true,
      footerTemplate: '<div style="font-size:8px;width:100%;text-align:center;color:#666"><span class="pageNumber"></span>/<span class="totalPages"></span></div>',
      format: "A4",
      headerTemplate: "<div></div>",
      margin: { bottom: "20mm", left: "15mm", right: "15mm", top: "20mm" },
      printBackground: true,
    });
    await page.close();
    return {
      bytes: Buffer.from(bytes),
      fileName: markdownFileName.replace(/\.md$/i, ".pdf"),
    };
  } finally {
    await browser.close();
  }
}
