export const windowsShellHygieneRule =
  "- If the available shell is PowerShell on Windows, never redirect output to `nul`; PowerShell creates a real file named `nul`. Use `$null`, `Out-Null`, or `2>$null` instead, and delete any accidental `nul` file immediately with `Remove-Item -LiteralPath .\\nul -Force`.";

export const lessonsLearnedExecutionConstraintsRule =
  "- Treat Project LessonsLearned Active Rules as executable constraints. If they define command sequencing, serialization, lock handling, shell behavior, install limits, provider retry handling, or any other project/tooling safety rule, obey those lessons even when FeatureTasks.md or a phase file is silent.";

export const sharedCodeQualityAssumptionsRule =
  "- Shared code-quality assumptions (Developer and Code Review): this project is in development, so an internal phase contract defaults to `BREAKING CHANGE PERMITTED`. Use the current V1 contract for internal versioned protocols; an internal `LEGACY_*` selector, local caller, fixture, or development data is not authority to retain a legacy lane. Use `BACKWARD COMPATIBILITY REQUIRED` only when an approved Feature/EPIC requirement or a public deployed-contract requirement explicitly requires it; a review finding, planning narrative, test, local caller, old Feature/EPIC, fixture, or development data cannot create that requirement. Every BLOCKER/REQUIRED finding that changes a function, schema, or behavioural contract must state `Compatibility Decision: BREAKING CHANGE PERMITTED` or `Compatibility Decision: BACKWARD COMPATIBILITY REQUIRED`, required caller migration, and forbidden fallbacks. A backward-compatibility decision must also state the authoritative approval source and a concrete justification naming the external deployed consumer, customer-retention obligation, or approved release/migration constraint; otherwise use `BREAKING CHANGE PERMITTED`. For a breaking decision, update production callers, fixtures, and development artifacts and do not retain an optional, hash-only, legacy, or context-free bypass. An optional parameter is acceptable only when its absence is explicitly valid; when absence must reject, test that rejection and never claim a compatibility path as a fix.";

export const serializedBuildCommandsSkillRule =
  "- Before running build, test, lint, format, or verification commands, apply the `serialized-build-commands` skill when available. Treat its execution workflow as mandatory for shared-state tools and combine it with Project LessonsLearned Active Rules. Cargo invocations may be sequential within one foreground shell tool call. Never background Cargo or emit sibling Cargo tool calls in one assistant message because Pi may execute siblings concurrently; wait for the complete foreground result before starting another Cargo tool call.";

export const cargoValidationLadderRule =
  "- For Rust validation, use the Cargo validation ladder: focused changed-file/exact tests first, then touched module/group tests, then business-area tests (palette/completion/acceptance/Gherkin), and run broad full-suite commands such as `cargo test -p codewhale-tui --bin codewhale-tui` only at phase checkpoint/final gate or when shared infrastructure changes require that blast radius.";

export const validationEvidenceAccountingRule =
  "- Validation evidence must account for every attempt. If a build/test/lint command times out, fails, is interrupted, or is retried, record each attempt separately with command, result, elapsed time when available, retry reason, and final outcome. The evidence summary must include total wall-clock validation time from the first attempt to the final pass/blocker; never report only the successful retry duration as if it were the whole validation time.";

export const cargoTimeoutSafetyRule =
  "- If a Cargo command times out or is interrupted, assume a cargo/rustc child process may still be alive. Before starting any other Cargo command, inspect for active cargo/rustc processes or Cargo lock waits, record what you found, and wait/clean up safely instead of launching a competing Cargo process.";

export const phaseTaskLedgerRule =
  "- Treat markdown task checkboxes in the current phase document as the bootstrap resume ledger: existing `[x]` items are COMPLETED even when SQLite task rows or the `## Hepha Task State` table do not exist yet, and the next unchecked checkbox is the next executable task. Checked items must not be rerun unless a later changed file, failed verification, or review-finding decision explicitly invalidates them. The Phase Task Ledger, `## Hepha Task State`, lifecycle status, FeatureTasks status, and Quality Gate Evidence decision cells are machine-owned: do not add, remove, reorder, check, uncheck, rename, or annotate ledger tasks; do not derive phase eligibility from historical report prose. Hepha alone updates those fields from durable workflow events. Hepha mirrors task state to SQLite and the phase Markdown `## Hepha Task State` table with NOT_STARTED, IN_PROGRESS, COMPLETED, SKIPPED, Started, Completed, and Duration fields.";

export const codeReviewFindingLedgerRule =
  "- In Resolve Findings, create or update a Review Finding Decision Ledger for every latest review finding, including BLOCKER, REQUIRED, WITH_NOTES, NON_BLOCKING, POLISH, and OUT_OF_SCOPE. The ledger is supplementary evidence only: it never substitutes for the exact top-level `## Fixer Response` section in the latest code-review report. Under that exact heading, add `### F1`, `### F2`, etc. for every BLOCKER/REQUIRED finding. The fixer records a Fixer Decision, never a final review decision: exactly `FIX_PROPOSED`, `REBUTTAL_PROPOSED`, `OUTSIDE_OF_SCOPE`, `ACCEPT_REFRAME`, `REJECT_REFRAME`, or `BLOCKED_NEEDS_USER`. Never use aliases such as fixed, blocked, or rebutted. A `FIX_PROPOSED` or `ACCEPT_REFRAME` must name the changed production symbols, map every reviewer acceptance-evidence item to an exact test/check, and record its executed passing result. A failed, skipped, or crashing acceptance test means the proposal is incomplete, not fixed. For BLOCKER/REQUIRED, a rebuttal must state its contract basis and measurable evidence, and it remains proposed until the independent reviewer explicitly accepts or rejects it. Scope arbitration is a one-shot, auditable protocol: use `OUTSIDE_OF_SCOPE` when the requested work is not owned by this phase; cite exact phase scope/task/acceptance evidence, identify the requested work that lies outside it, and provide measurable source/planning evidence. The reviewer may either record it in TechnicalDebts or issue one detailed `REFRAME_INTO_SCOPE`; only after that reframe may the fixer use `ACCEPT_REFRAME` (implement the complete reframed contract) or `REJECT_REFRAME` (detailed scope evidence; no implementation). A rejected reframe must become TechnicalDebt, never another reframe or fixer loop. Only the reviewer may use `FIX_ACCEPTED`, `REBUTTAL_ACCEPTED_DEFERRED`, `REBUTTAL_REJECTED`, `REFRAME_INTO_SCOPE`, `FINDING_OPEN`, `NOT_APPLICABLE`, or `BLOCKED_NEEDS_USER`; do not write fixed, rebutted, deferred, accepted, or closed as a fixer decision. If the reviewer rejects a rebuttal, keep the same finding ID open and implement the required code change; escalate only a genuine contract ambiguity as blocked_needs_user. Complete every required stale-claim sweep across touched docs/code comments before proposing a rerun. Record `Review fixes applied; awaiting independent code review rerun` only as narrative evidence. Never put it—or any prose—in `**Status:**`, FeatureTasks Status, or the Quality Gate Evidence Decision column: Hepha owns those machine fields.";

export const featurePlanningArtifactFileName = "planning-analysis-report.md";
export const epicAcceptanceTestsFileName = "EpicAcceptanceTests.md";
