/**
 * FEAT-056: Workflow And Phase Interaction Decomposition
 *
 * Phase 4 — Presentation Logic: pure presentation selectors and formatters.
 *
 * These functions transform authoritative workflow facts into UI-ready
 * display models. They do NOT:
 * - Evaluate readiness, recovery, completion, or eligibility predicates
 * - Access React state, JSX, or DOM
 * - Read files, databases, or metadata
 */

import type {
  FeatureWorkflowSummary,
  FeatureWorkflowRunSummary,
  FeatureImplementationEvidenceSummary,
  ImplementationAgentRunSummary,
  ImplementationPhaseRunSummary,
  PhaseSummary,
  FeatureFindingSummary,
  FeatReadinessReason,
  ManualTestPackDashboardStatus,
  TerminalWorkItemLifecycle,
} from "@hepha/shared";
import {
  buildFeatureTimingAnalytics,
  buildTimingAnalyticsFromEstimates,
  formatEffortEstimateRange,
} from "@hepha/shared";

import {
  formatStatusLabel,
  formatWorkflowCommand,
  sortPhasesByNumber,
  findCurrentPhase,
  getBlockingReadinessReasons,
} from "./workflow-mappers.js";
import {
  buildPhaseExecutionTelemetry,
  completedDurationMs as getCompletedDurationMs,
} from "./phase-execution-telemetry.js";

// ─── Display model types ────────────────────────────────────────────────────

export interface OverviewDisplay {
  readonly title: string;
  readonly readinessLabel: string;
  readonly readinessIcon: "success" | "warning" | "blocked";
  readonly hasActiveRun: boolean;
  readonly activeRunCommand: string | null;
  readonly activeRunStep: string | null;
  readonly lastRunStatus: string | null;
  readonly lastRunCommand: string | null;
  readonly lastRunSummary: string | null;
  readonly workflowMessage: string | null;
  /** Exact server-authoritative reasons that make the current workflow blocked. */
  readonly blockingReasons?: readonly FeatReadinessReason[];
  /** Ordered persisted workflow nodes, including transition and post-process work. */
  readonly workflowSteps?: readonly {
    readonly id: string;
    readonly label: string;
    readonly detail: string | null;
    readonly status: "pending" | "running" | "completed" | "failed";
  }[];
}

export interface PhaseRuntimeExecutionDisplay {
  readonly id: string;
  readonly workflowRunId: string;
  readonly agent: string;
  readonly commandModel: string | null;
  readonly startedAt: string;
  readonly completedAt: string | null;
  readonly durationMs: number | null;
  readonly status: string;
}

export interface PhaseRowDisplay {
  readonly executionContractId?: string | null;
  readonly number: number | null;
  readonly title: string;
  readonly status: string;
  readonly statusLabel: string;
  readonly isCurrent: boolean;
  readonly isCompleted: boolean;
  readonly isBlocked: boolean;
  readonly isActive: boolean;
  /** Exact persisted activity for the active agent, including recovery work. */
  readonly activityLabel: string | null;
  readonly hasError: boolean;
  readonly errorMessage: string | null;
  readonly agent: string | null;
  /** Model selected by the orchestrator command; observed runtime routes remain separate evidence. */
  readonly model: string | null;
  readonly modelSource: "orchestrator_command" | "phase_prediction" | "workflow_default" | null;
  /** Phase-attributed immutable agent executions, including reconciled legacy segments. */
  readonly runtimeExecutions: readonly PhaseRuntimeExecutionDisplay[];
  /** Estimates are generated by Start Feature post-processing. */
  readonly estimatedHumanTime: string | null;
  readonly estimatedAiTime: string | null;
  /** Cumulative settled AI-agent wall-clock duration attributed to this phase. */
  readonly actualDurationMs: number | null;
  readonly aiEstimateAssessment: "under" | "within" | "over" | null;
  readonly aiBoundaryDeltaMs: number | null;
  readonly estimatedHumanTimeSavedMidpointMs: number | null;
  readonly humanAccelerationMidpoint: number | null;
  readonly evidence?: {
    readonly codeFileCount: number;
    readonly testFileCount: number;
    readonly documentationFileCount: number;
    readonly warnings: readonly string[];
    readonly gates: readonly {
      readonly gate: string;
      readonly status: string;
      readonly justification: string | null;
    }[];
  } | null;
}

export interface FeatureTimingSummaryDisplay {
  readonly estimatedHumanTime: string | null;
  readonly estimatedAiTime: string | null;
  /** Sum of all persisted, ended implementation-agent executions for the FEAT. */
  readonly actualDurationMs: number | null;
  /** Completed execution plus currently running persisted agent runtime. */
  readonly inProgressDurationMs: number | null;
  readonly aiEstimateAssessment: "under" | "within" | "over" | null;
  readonly aiBoundaryDeltaMs: number | null;
  readonly aiMidpointErrorPercent: number | null;
  readonly estimatedHumanTimeSavedMidpointMs: number | null;
  readonly humanAccelerationMidpoint: number | null;
}

export interface RecoveryActionDisplay {
  readonly type: "ui_requirement" | "design_artifact" | "deep_dive" | "other";
  readonly label: string;
  readonly description: string;
  readonly available: boolean;
}

export interface HumanVerificationSummaryDisplay {
  readonly manualTestState: ManualTestPackSummaryState;
  readonly manualTestMessage: string;
  readonly userCodeReviewDone: boolean;
  readonly userCodeReviewTimestamp: string | null;
  readonly manualTestsDone: boolean;
}

export type ManualTestPackSummaryState =
  | "missing"
  | "generating"
  | "current"
  | "stale"
  | "render_failed"
  | "reviewed"
  | "incomplete"
  | "not_applicable";

export interface FindingDisplay {
  readonly id: string;
  readonly title: string;
  readonly status: string;
  readonly statusLabel: string;
  readonly summary: string | null;
  readonly isOpen: boolean;
  readonly isAgentRunning: boolean;
  readonly isClosed: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly lastEventPreview: string | null;
}

export interface CompletionReadinessDisplay {
  readonly verdict: CompletionVerdict;
  readonly reasons: readonly string[];
  readonly canCompleteNow: boolean;
  readonly isFinalizing: boolean;
  readonly missingQualityGateCount: number;
}

export type CompletionVerdict =
  | "ready"
  | "blocked"
  | "finalizing"
  | "not_applicable";

// ─── Overview display ───────────────────────────────────────────────────────

export function buildOverviewDisplay(
  workflow: FeatureWorkflowSummary | null,
  terminalLifecycle: TerminalWorkItemLifecycle | null = null,
): OverviewDisplay {
  if (!workflow) {
    return {
      title: "Workflow",
      readinessLabel: "Not available",
      readinessIcon: "warning",
      hasActiveRun: false,
      activeRunCommand: null,
      activeRunStep: null,
      lastRunStatus: null,
      lastRunCommand: null,
      lastRunSummary: null,
      workflowMessage: null,
      blockingReasons: [],
      workflowSteps: [],
    };
  }

  // A terminal filesystem/document state is authoritative. Ignore any stale
  // active-run projection left behind by an interrupted orchestrator.
  const activeRun = terminalLifecycle ? null : workflow.activeRun;
  const lastRun = workflow.lastRun;
  const blockingReasons = getBlockingReadinessReasons(workflow);

  return {
    title: "Workflow",
    // A running workflow owns an active transition. Terminal lifecycle state
    // remains authoritative over stale runtime metadata.
    readinessLabel: terminalLifecycle === "completed"
      ? "Completed"
      : terminalLifecycle === "cancelled"
        ? "Cancelled"
        : activeRun
          ? "Running"
          : workflow.canContinueImplementing
            ? "Ready to continue"
            : workflow.implementationCompleted
              ? "Implementation complete"
              : workflow.readiness?.ready
                ? "Ready"
                : blockingReasons.length > 0
                  ? "Blocked"
                  : "Not ready",
    readinessIcon: terminalLifecycle === "completed" || activeRun || workflow.canContinueImplementing ||
      workflow.implementationCompleted || workflow.readiness?.ready
      ? "success"
      : blockingReasons.length > 0
        ? "blocked"
        : "warning",
    hasActiveRun: activeRun !== null,
    activeRunCommand: activeRun ? formatWorkflowCommand(activeRun.command) : null,
    activeRunStep: activeRun?.currentStep ?? null,
    lastRunStatus: lastRun ? formatStatusLabel(lastRun.status) : null,
    lastRunCommand: lastRun ? formatWorkflowCommand(lastRun.command) : null,
    lastRunSummary: compactWorkflowFailureDisplay(lastRun?.summary ?? null),
    workflowMessage: compactWorkflowFailureDisplay(workflow.workflowMessage || null),
    blockingReasons,
    workflowSteps: activeRun?.workflowProgress?.steps ?? [],
  };
}

function compactWorkflowFailureDisplay(value: string | null): string | null {
  if (!value || value.length <= 900) {
    return value;
  }

  const reportPath = [...value.matchAll(/(?:See|Review report:\s*)([^\s]+phase-\d+-code-review-[^\s]+\.md)/gi)]
    .at(-1)?.[1];
  const finding = value.match(/-\s+(F\d+\s+\[REQUIRED\/[^\n]+)/i)?.[1];

  if (!reportPath && !finding) {
    return value;
  }

  const parts = ["Code-review gate needs changes."];
  if (reportPath) parts.push(`Latest report: ${reportPath.split(/[\\/]/).at(-1)}.`);
  if (finding) {
    const readableFinding = finding
      .replace(/\s+/g, " ")
      .replace(/\s+(?=(?:Location|Finding|Required change|Decision requirement):)/gi, "\n")
      .trim();
    parts.push(`Current finding: ${readableFinding}`);
  }
  // This is displayed directly in WorkflowMessage. Preserve boundaries so its
  // field renderer (and the pre-wrap fallback) can present the failure as
  // readable lines instead of one dense paragraph.
  return parts.join("\n");
}

// ─── Phase rows ─────────────────────────────────────────────────────────────

export function buildPhaseRows(
  phases: readonly PhaseSummary[],
  implementationPhases: readonly ImplementationPhaseRunSummary[],
  _currentItemId: string | null = null,
  qualityEvidence: readonly FeatureImplementationEvidenceSummary["phaseQualityGates"][number][] = [],
  implementationAgentRuns: readonly ImplementationAgentRunSummary[] = [],
  defaultImplementationModel: string | null = null,
  refineCompletedAt: string | null = null,
): readonly PhaseRowDisplay[] {
  // Planning reports are supporting artifacts, not lifecycle phases. Keep the
  // operator's one phase list strictly numbered and lifecycle-authoritative.
  const sorted = sortPhasesByNumber(phases).filter((phase): phase is PhaseSummary & { number: number } => phase.number !== null);
  const currentPhase = findCurrentPhase(sorted);
  const phaseTelemetry = buildPhaseExecutionTelemetry(
    sorted, implementationPhases, implementationAgentRuns, refineCompletedAt,
  );

  return sorted.map((phase) => {
    // A phase can span the start workflow and one or more continuation runs.
    // Use the latest persisted record for the phase rather than hiding prior
    // execution timing when the latest workflow run has a different id.
    const implRun = selectLatestPhaseRun(implementationPhases, phase.number);
    const telemetry = phaseTelemetry.get(phase.number)!;
    const latestAgentRun = telemetry.latestAgentRun;
    const evidence = qualityEvidence.find((candidate) => candidate.phaseNumber === phase.number) ?? null;
    const isRecovery = implRun?.status === "checkpoint" && implRun.agent === "Workflow Recovery Agent";
    const hasActiveRuntime = implRun?.status === "implementing" || implRun?.status === "code_review" || isRecovery;
    const hasInProgressLifecycle = phase.status.trim().toLowerCase().replace(/[\s-]+/g, "_") === "in_progress";
    // Lifecycle and runtime activity are independent evidence. A compatibility
    // worker can durably activate the next phase before a new phase-bound
    // runtime record exists, so either source must make the row visibly active.
    const isActive = hasActiveRuntime || hasInProgressLifecycle;
    // Runtime phase state is newer than the Markdown rescan while a worker is
    // active. This prevents an active phase being labelled Pending until the
    // worker has had a chance to update its durable phase document.
    const displayStatus = isRecovery ? "recovering" : hasActiveRuntime ? implRun!.status : phase.status;
    const actualDurationMs = telemetry.actualDurationMs;
    const modelProjection = projectPhaseCommandModel(phase, implRun, latestAgentRun, defaultImplementationModel);
    const timingAnalytics = buildTimingAnalyticsFromEstimates(
      phase.estimatedHumanTime,
      phase.estimatedAiTime,
      actualDurationMs,
    );

    return {
      executionContractId: phase.executionContractId,
      number: phase.number,
      title: phase.title,
      status: displayStatus,
      statusLabel: formatStatusLabel(displayStatus),
      isCurrent: currentPhase?.number === phase.number,
      isCompleted: phase.status === "completed" || phase.status === "COMPLETED",
      isBlocked: phase.status === "blocked" || phase.status === "BLOCKED",
      isActive,
      activityLabel: isActive ? implRun?.currentStep ?? null : null,
      hasError: implRun?.error !== null && implRun?.error !== undefined,
      errorMessage: implRun?.error ?? null,
      agent: implRun?.agent ?? latestAgentRun?.agentName ?? (modelProjection.model ? "Orchestrator" : null),
      model: modelProjection.model,
      modelSource: modelProjection.source,
      runtimeExecutions: telemetry.agentRuns.map((run) => ({
        id: run.id,
        workflowRunId: run.workflowRunId,
        agent: run.agentName,
        commandModel: run.model === "not-recorded" ? modelProjection.model : run.model,
        startedAt: run.startedAt,
        completedAt: run.completedAt,
        durationMs: getCompletedDurationMs(run.startedAt, run.completedAt),
        status: run.status,
      })),
      estimatedHumanTime: phase.estimatedHumanTime,
      estimatedAiTime: phase.estimatedAiTime,
      // Sum every completed attempt for the phase. A retry/continuation is a
      // new workflow run and must add to, never replace, prior actual time.
      actualDurationMs,
      aiEstimateAssessment: timingAnalytics.aiEstimateAssessment,
      aiBoundaryDeltaMs: timingAnalytics.aiBoundaryDeltaMs,
      estimatedHumanTimeSavedMidpointMs: timingAnalytics.estimatedHumanTimeSavedMidpointMs,
      humanAccelerationMidpoint: timingAnalytics.humanAccelerationMidpoint,
      // Quality-gate plans remain visible before execution. They show the
      // operator what each phase will need; only execution timing waits for
      // Start Feature post-processing and completed worker runs.
      evidence: evidence
        ? {
          codeFileCount: evidence.codeFiles.length,
          testFileCount: evidence.testFiles.length,
          documentationFileCount: evidence.documentationFiles.length,
          warnings: evidence.warnings,
          gates: evidence.gates.map((gate) => ({
            gate: gate.gate,
            status: gate.status,
            justification: gate.justification,
          })),
        }
        : null,
    };
  });
}

/**
 * Aggregate post-process estimates and the persisted agent executions for a
 * FEAT. Phase-worker timing remains available in phase rows, but the feature
 * total must include every agent role (including post-process and recovery).
 * Estimates are withheld when incomplete; runtime telemetry is not.
 */
export function buildFeatureTimingSummary(
  phases: readonly PhaseSummary[],
  _implementationPhases: readonly ImplementationPhaseRunSummary[],
  implementationAgentRuns: readonly ImplementationAgentRunSummary[] = [],
  nowMs = Date.now(),
): FeatureTimingSummaryDisplay {
  const analytics = buildFeatureTimingAnalytics(phases, implementationAgentRuns);
  // A terminal failed/blocked agent has also consumed real AI runtime. Its
  // completed_at timestamp marks the end of an execution and is intentionally
  // included rather than hiding recovery cost from the feature total.
  const completedDurationMs = implementationAgentRuns
    .map((agentRun) => getCompletedDurationMs(agentRun.startedAt, agentRun.completedAt))
    .filter((duration): duration is number => duration !== null)
    .reduce((total, duration) => total + duration, 0);
  const hasCompletedExecution = implementationAgentRuns.some(
    (agentRun) => getCompletedDurationMs(agentRun.startedAt, agentRun.completedAt) !== null,
  );
  const activeDurationMs = implementationAgentRuns
    .filter((agentRun) => agentRun.status === "running")
    .map((agentRun) => getRunningDurationMs(agentRun.startedAt, nowMs))
    .filter((duration): duration is number => duration !== null)
    .reduce((total, duration) => total + duration, 0);
  const hasRunningExecution = implementationAgentRuns.some(
    (agentRun) => agentRun.status === "running" && getRunningDurationMs(agentRun.startedAt, nowMs) !== null,
  );

  return {
    estimatedHumanTime: formatEffortEstimateRange(analytics.humanEstimate),
    estimatedAiTime: formatEffortEstimateRange(analytics.aiEstimate),
    actualDurationMs: hasCompletedExecution ? completedDurationMs : null,
    inProgressDurationMs: hasRunningExecution ? completedDurationMs + activeDurationMs : null,
    aiEstimateAssessment: analytics.aiEstimateAssessment,
    aiBoundaryDeltaMs: analytics.aiBoundaryDeltaMs,
    aiMidpointErrorPercent: analytics.aiMidpointErrorPercent,
    estimatedHumanTimeSavedMidpointMs: analytics.estimatedHumanTimeSavedMidpointMs,
    humanAccelerationMidpoint: analytics.humanAccelerationMidpoint,
  };
}

function selectLatestPhaseRun(
  implementationPhases: readonly ImplementationPhaseRunSummary[],
  phaseNumber: number,
): ImplementationPhaseRunSummary | null {
  const candidates = implementationPhases.filter((phase) => phase.phaseNumber === phaseNumber);

  if (candidates.length === 0) return null;

  return candidates.reduce((latest, candidate) =>
    Date.parse(candidate.updatedAt) > Date.parse(latest.updatedAt) ? candidate : latest,
  );
}

function getRunningDurationMs(startedAt: string, nowMs: number) {
  const startedAtMs = Date.parse(startedAt);
  const duration = nowMs - startedAtMs;
  return Number.isFinite(duration) && duration >= 0 ? duration : null;
}


function projectPhaseCommandModel(
  phase: PhaseSummary,
  phaseRun: ImplementationPhaseRunSummary | null,
  agentRun: ImplementationAgentRunSummary | null,
  workflowDefault: string | null,
): { readonly model: string | null; readonly source: PhaseRowDisplay["modelSource"] } {
  const recorded = [phaseRun?.model, agentRun?.model].find((value) =>
    Boolean(value && value !== "not-recorded"),
  ) ?? null;
  if (recorded) return { model: recorded, source: "orchestrator_command" };
  if (phase.predictedModel) return { model: phase.predictedModel, source: "phase_prediction" };
  const fallback = phase.defaultImplementationModel ?? workflowDefault;
  return fallback
    ? { model: fallback, source: "workflow_default" }
    : { model: null, source: null };
}

function isSkippedPhaseStatus(status: string) {
  return /^(skipped|n\/a)$/i.test(status.trim());
}

function isResolvedPhaseStatus(status: string) {
  return /^(completed|complete|skipped|n\/a)$/i.test(status.trim());
}

// ─── Recovery actions ───────────────────────────────────────────────────────

export function buildRecoveryActions(
  workflow: FeatureWorkflowSummary | null,
  terminalLifecycle: TerminalWorkItemLifecycle | null = null,
): readonly RecoveryActionDisplay[] {
  // Recovery actions would start a conflicting workflow while implementation
  // owns this FEAT. Show them only after the active run has stopped.
  if (!workflow || workflow.activeRun || terminalLifecycle) return [];

  const actions: RecoveryActionDisplay[] = [];
  const reasons = getBlockingReadinessReasons(workflow);
  const refinementNeedsDeepDive = workflow.lastRun?.command === "refine-feature" &&
    (workflow.lastRun.status === "blocked" || workflow.lastRun.status === "completed") &&
    !workflow.hasRefinementArtifacts;

  // A refinement worker may discover a target decision after source markers
  // were consumed. This current-action blocker is authoritative even though
  // historical receipts and source hashes remain audit-only evidence.
  if (refinementNeedsDeepDive) {
    const continuing = workflow.lastRun?.status === "blocked";
    return [{
      type: "deep_dive",
      label: continuing ? "Continue FEAT Deep-Dive" : "Start FEAT Deep-Dive",
      description: workflow.lastRun?.summary ?? "Resolve the target decisions discovered during refinement.",
      available: true,
    }];
  }

  // Unresolved validation markers are the source-document authority for
  // requiring a Deep-Dive before an operation has discovered a new decision.
  if (reasons.some((reason) => reason.blocking && reason.code === "validation_markers_present")) {
    const continuing = workflow.lastRun?.command === "refine-feature" && workflow.lastRun.status === "blocked";
    return [{
      type: "deep_dive",
      label: continuing ? "Continue FEAT Deep-Dive" : "Start FEAT Deep-Dive",
      description: continuing
        ? workflow.lastRun?.summary ?? "Resolve the validation markers discovered during refinement."
        : "Resolve the validation markers in the FEAT specification.",
      available: true,
    }];
  }

  if (reasons.some((r) => r.blocking && r.code === "ui_requirement_unknown")) {
    actions.push({
      type: "ui_requirement",
      label: "Check UI Requirement",
      description: "Classify whether this FEAT needs UI requirements before implementation can continue.",
      available: true,
    });
  }

  if (
    reasons.some((r) => r.blocking && r.code === "missing_design_artifacts") &&
    workflow.uiRequirementDecision === "requires_ui"
  ) {
    actions.push({
      type: "design_artifact",
      label: "Design Feature",
      description: "Create UX research, wireframes, and design summary for this FEAT.",
      available: workflow.canCreateUiRequirements,
    });
  }

  return actions;
}

// ─── Human verification summary ─────────────────────────────────────────────

export function buildHumanVerificationSummary(
  workflow: FeatureWorkflowSummary | null,
): HumanVerificationSummaryDisplay {
  if (!workflow) {
    return {
      manualTestState: "missing",
      manualTestMessage: "No manual test data available.",
      userCodeReviewDone: false,
      userCodeReviewTimestamp: null,
      manualTestsDone: false,
    };
  }

  const packStatus = workflow.manualTestPackStatus;
  let manualTestState: ManualTestPackSummaryState = "missing";
  let manualTestMessage = "No manual test pack generated.";

  if (packStatus) {
    if (packStatus.applicability === "not_applicable") {
      manualTestState = "not_applicable";
      manualTestMessage = "Manual Tests: Not Applicable.";
    } else if (packStatus.applicability === "incomplete") {
      manualTestState = "incomplete";
      manualTestMessage = packStatus.message || "Manual test package is incomplete.";
    } else if (packStatus.state === "generating") {
      manualTestState = "generating";
      manualTestMessage = "Test pack is being generated.";
    } else if (packStatus.state === "current" || packStatus.state === "stale") {
      if (packStatus.isReviewed && packStatus.hasResults) {
        manualTestState = "reviewed";
        manualTestMessage = `Reviewed: ${packStatus.passedCount} passed, ${packStatus.failedCount} failed.`;
      } else if (packStatus.isReviewed) {
        manualTestState = "reviewed";
        manualTestMessage = "Test pack reviewed, no results recorded.";
      } else if (packStatus.state === "stale") {
        manualTestState = "stale";
        manualTestMessage = "Test pack is stale; regenerate for current state.";
      } else if (packStatus.isReady) {
        manualTestState = "current";
        manualTestMessage = "Test pack ready for review.";
      } else {
        manualTestState = "incomplete";
        manualTestMessage = "Manual test package is incomplete.";
      }
    } else if (packStatus.state === "render_failed") {
      manualTestState = "render_failed";
      manualTestMessage = packStatus.message || "Test pack generation failed.";
    }

    if (packStatus.hasResults && packStatus.failedCount > 0 && !packStatus.isReviewed) {
      manualTestState = "incomplete";
      manualTestMessage = `${packStatus.failedCount} test(s) failed; review required.`;
    }
  }

  return {
    manualTestState,
    manualTestMessage,
    userCodeReviewDone: !!workflow.userCodeReviewCompletedAt,
    userCodeReviewTimestamp: workflow.userCodeReviewCompletedAt ?? null,
    manualTestsDone: !!workflow.manualTestsCompletedAt,
  };
}

// ─── Finding display ────────────────────────────────────────────────────────

export function buildFindingDisplay(
  finding: FeatureFindingSummary,
): FindingDisplay {
  const lastEvent = finding.events[finding.events.length - 1];

  return {
    id: finding.id,
    title: finding.title,
    status: finding.status,
    statusLabel: formatFindingStatus(finding.status),
    isOpen: finding.status === "open",
    isAgentRunning: finding.status === "agent_running",
    isClosed: finding.status === "closed",
    createdAt: finding.createdAt,
    updatedAt: finding.updatedAt,
    summary: finding.summary,
    lastEventPreview: lastEvent?.content
      ? lastEvent.content.length > 100
        ? lastEvent.content.substring(0, 100) + "..."
        : lastEvent.content
      : null,
  };
}

function formatFindingStatus(status: string): string {
  const labels: Record<string, string> = {
    open: "Open",
    agent_running: "Investigating",
    agent_response: "Response Ready",
    closed: "Resolved",
  };
  return labels[status] ?? status;
}

// ─── Completion readiness ───────────────────────────────────────────────────

export function summarizeResolvedPhaseQualityGates(
  phases: FeatureImplementationEvidenceSummary["phaseQualityGates"],
): { readonly missing: number; readonly total: number } {
  return phases.reduce(
    (summary, phase) => {
      const status = phase.phaseStatus.trim().toUpperCase();
      if (status !== "COMPLETED" && status !== "SKIPPED") return summary;
      return {
        missing: summary.missing + phase.gates.filter((gate) => gate.status === "missing").length,
        total: summary.total + phase.gates.length,
      };
    },
    { missing: 0, total: 0 },
  );
}

export function buildCompletionReadiness(
  workflow: FeatureWorkflowSummary | null,
  qualityGateCount: number,
  gateSummary: { missing: number; total: number },
  terminalLifecycle: TerminalWorkItemLifecycle | null = null,
): CompletionReadinessDisplay {
  if (!workflow || terminalLifecycle) {
    return {
      verdict: "not_applicable",
      reasons: ["No workflow data available."],
      canCompleteNow: false,
      isFinalizing: false,
      missingQualityGateCount: 0,
    };
  }

  const reasons: string[] = [];
  let canCompleteNow = true;

  // Priority 1: Active run means finalizing is in progress
  let verdict: CompletionVerdict = workflow.activeRun ? "finalizing" : "ready";

  if (workflow.activeRun) {
    reasons.push("A workflow run is in progress.");
    canCompleteNow = false;
  }

  // Check implementation completed
  if (!workflow.implementationCompleted) {
    reasons.push("Implementation is not yet completed.");
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  // Check human review
  if (!workflow.userCodeReviewCompletedAt) {
    reasons.push("User code review is pending.");
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  if (!workflow.manualTestsCompletedAt) {
    reasons.push("Manual tests are pending.");
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  // Check open findings
  const openFindings = workflow.findings.filter((f) => f.status !== "closed");
  if (openFindings.length > 0) {
    reasons.push(`${openFindings.length} open finding(s) remain.`);
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  // Check quality gates
  if (gateSummary.missing > 0) {
    reasons.push(`${gateSummary.missing} phase quality gate(s) are missing.`);
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  // Check human review findings acceptance
  if (workflow.canAcceptHumanReviewFindings) {
    reasons.push("Accept human review findings before completing.");
    if (verdict === "ready") verdict = "blocked";
    canCompleteNow = false;
  }

  if (verdict === "ready") {
    reasons.push("All completion conditions satisfied.");
  }

  return {
    verdict,
    reasons,
    canCompleteNow,
    isFinalizing: verdict === "finalizing",
    missingQualityGateCount: gateSummary.missing,
  };
}
