/** One meaning of TestCoverage at implementation, phase repair and feature readiness. */
export const LOGICAL_ACCEPTANCE_COVERAGE_CONTRACT = [
  "Logical acceptance coverage: assess whether the existing integration tests and complementary tests logically prove the behavior required by this accepted FEAT plan, including only explicitly assigned parent obligations. Parent EPIC/project links never import unrelated criteria. Inspect setup, actions, assertions, shared steps, fixtures and implementation boundaries. NeedTestCoverage is this logical assessment, not a line/branch percentage or instrumentation requirement.",
  "Do not introduce new criteria, scenarios, risks or stronger verification boundaries at execution, review, repair or completion. Preserve the accepted acceptance-test report and its collective verification approach. An unimplemented capability or extra test outside the approved scope belongs in Lessons Learned as proposed-for-future-planning, never as a blocker or authority to implement it. Future approved work follows EPIC -> FEAT -> PHASE -> TASK -> CODE. Every blocker must quote an unmet accepted obligation. A current report must still establish actual execution, not merely discovery.",
  "Completion is fulfillment of the given plan, not a new Deep-Dive or Refinement. Follow the traceability chain EPIC requirements -> EPIC acceptance criteria -> FEAT acceptance criteria -> Phase/Task tests -> implementation. At the FEAT boundary, verify the assigned FEAT criteria and their accepted mappings upward and downward; a parent link or a test mentioned in historical notes does not by itself assign another completion obligation. Do not take over product planning by deciding what else the feature ought to do or test.",
  "Use current-source inspection findings, existing phase criterion-to-assertion mappings and their cited test bodies together. Trace delegated assertions and shared frontend/backend fixtures before declaring a test absent. Several tests can cover one criterion and one integration test can cover several criteria; names, counts and identical names across assemblies are not coverage judgments. Preserve the test boundaries explicitly required by the accepted contract.",
  "The accepted test report's allocation of behavior across browser, integration and component tests is part of the agreed verification approach. Assess that allocation before interpreting a broad criterion summary as requiring every alternative at every layer. A current inspection note saying an alternative did not run in one group is not a gap when another accepted group proves it. Trace common handlers and branch-independent delegation: equivalent entry points do not require duplicate end-to-end tests solely because they have different labels. If an actual required branch remains unasserted, cite that branch and the accepted obligation; hypothetical mutations outside the agreed verification approach belong to future improvements.",
  "Before requesting another test, inherited report or provenance record, identify the exact accepted FEAT obligation and assigned test boundary still unproved by the supplied applicable evidence collectively. If connected journeys prove the accepted flow and deterministic component or integration assertions prove the allocated alternatives, accept that combination. Do not make an additional historical browser journey mandatory for the same alternative merely because it is mentioned elsewhere. Historical findings, handoff notes and assessor preferences cannot override the accepted allocation. If that allocation explicitly requires the inherited journey, verify its evidence normally; never waive a declared obligation or claim an unexecuted test passed.",
  "Ask: Do these executed tests collectively fulfill the given acceptance criteria at the agreed boundaries? Do not ask: What further tests or requirements would make this product better? Suggestions for extra scenarios, stronger layers, broader risks or areas deserving more attention are non-blocking Lessons Learned for future approved Deep-Dive and Refinement. Keep a satisfied criterion satisfied when recording such a suggestion; do not disguise an optional improvement as missing evidence, missing provenance, investigation_required or an acceptance gap. Genuine missing evidence must explain which accepted obligation remains unverified and why the existing accepted combination cannot establish it.",
  "When existing assertions collectively establish the required behavior, recognize their coverage without asking for duplicate tests, a new coverage artifact, LCOV/Cobertura, measured lines, a percentage threshold or a numeric coverage policy. Missing numeric tooling is not a coverage finding or a reason to request clarification. Existing optional numeric telemetry is advisory and cannot substitute for this assessment.",
  "Separate logical alignment from execution: passing native results establish that tests ran; assertion-to-criterion reasoning establishes what they cover. A passing suite alone does not prove unasserted behavior. A source mapping alone does not prove a run. Missing execution is an execution finding, not missing test implementation. Reuse valid evidence for unchanged behavior.",
  "Any remaining logical coverage finding must identify the exact required behavior, the existing tests/shared helpers inspected, why their assertions do not prove it, and the smallest missing or incorrect assertion or implementation. Missing excerpts or unresolved references mean insufficient context, not proof that tests must be created. Earlier findings and sufficient verdicts must be checked against current source, never copied as authority.",
  "Authority remains action-specific: Refresh Readiness may inspect, run configured verification and report logical findings; it must not create tests or fix product code. The explicitly requested Phase Fixer corrects confirmed in-scope findings and reruns affected checks. Recognizing existing coverage does not create a new test or grant human acceptance.",
].join("\n\n");
