/** Renders the bounded fixer, scope-arbitration, durability, and rerun protocol for a phase. */
export function renderPhaseReviewRemediationRules(successorRules: readonly string[] = []) {
  return [
    "- If the Previous Workflow Failure Brief contains a Code Review Blocker, treat every listed Review Finding Decision Queue item as the first task for this phase even when the phase file already says COMPLETED.",
    "- The reviewer-owned finding text is immutable. Before any review rerun, append or update one exact top-level `## Fixer Response` section in the latest saved review report, then place `### F1`, `### F2`, etc. beneath that section for every BLOCKER/REQUIRED finding. A Review Finding Decision Ledger is separate evidence and never substitutes for this exact `## Fixer Response` section. Use exactly one `Fixer Decision`: `FIX_PROPOSED`, `REBUTTAL_PROPOSED`, `OUTSIDE_OF_SCOPE`, `ACCEPT_REFRAME`, `REJECT_REFRAME`, or `BLOCKED_NEEDS_USER`; do not use prose synonyms such as Fixed/Rebutted/Deferred. Every response needs `Files` or `Files / symbols` and `Verification` with the exact focused command/result. A `FIX_PROPOSED` or `ACCEPT_REFRAME` also needs `Acceptance evidence` or `Measured evidence` mapping every reviewer acceptance item to an executed passing test/check. `REBUTTAL_PROPOSED`, `OUTSIDE_OF_SCOPE`, and `REJECT_REFRAME` additionally require detailed `Argument`, `Contract basis`, or `Scope basis` plus `Acceptance evidence` or `Measured evidence`. A fixer cannot mark a finding accepted, deferred, or closed; only the next independent reviewer may do that.",
    "- When the current workflow step is Resolve Plan Review Findings or Resolve Code Review Findings, do not resume normal phase implementation. Resolve the review-finding decision queue, then record `Review fixes applied; awaiting independent code review rerun` as narrative evidence only. Hepha, not the worker, will set `AWAITING_REVIEW` and the code-review decision token.",
    ...successorRules,
    "- Code-review recovery work can be documentation-only, MemoryBank-only, git-state-only, or whitespace-only. An empty project source diff does not mean there is no recovery work.",
    "- Scope guardrail: reject any review request that is outside this phase's approved scope. Use `OUTSIDE_OF_SCOPE`, not a code change, and give a detailed auditable justification: exact phase task/acceptance/production-target citations, the requested work that exceeds them, the owner/phase that should own it if known, and measurable source/planning evidence. The reviewer then either records TechnicalDebt or issues one detailed `REFRAME_INTO_SCOPE`. Only after that exact reviewer state may you choose `ACCEPT_REFRAME` (implement the complete reframed contract with normal fix evidence) or `REJECT_REFRAME` (do not implement; provide detailed scope evidence). A `REJECT_REFRAME` ends the review change path: the reviewer must add TechnicalDebt and may not submit another reframe. Never use `OUTSIDE_OF_SCOPE` after a reframe.",
    "- For every finding, write exactly one Fixer Decision: `FIX_PROPOSED`, `REBUTTAL_PROPOSED`, `OUTSIDE_OF_SCOPE`, `ACCEPT_REFRAME`, `REJECT_REFRAME`, or `BLOCKED_NEEDS_USER`. These are proposals, not final outcomes. Do not write fixed, deferred, accepted, rebutted, closed, or accepted_risk as the fixer decision. For BLOCKER/REQUIRED, implement the requested code fix unless you have a substantiated rebuttal or a documented scope rejection. A rejected rebuttal is not a new finding and must return to the same finding ID for a code fix. Escalate only a genuine contract ambiguity as `BLOCKED_NEEDS_USER`.",
    "- Change only the files needed by BLOCKER/REQUIRED fixes or explicitly chosen note decisions. Do not rewrite unrelated sections, introduce new evidence formats, add hashes/timestamps, or reopen PlanReviewer-approved planning scope unless a finding explicitly requires it.",
    "- For a contract planning/evidence-only phase or documentation-only code-review recovery, do not run Cargo just because older source-state gates mention `cargo check`. Use documentation/source-audit checks such as `git diff --check`, `git status`, `rg`, and exact file reads unless a BLOCKER/REQUIRED finding explicitly asks for build evidence or you changed Rust source files.",
    "- If a review finding only concerns MemoryBank/planning documents, verification should prove the document claim changed correctly and remained whitespace-clean; it should not start a Rust build.",
    "- Before requesting a code-review rerun, inspect every previous finding and list it in a Review Finding Decision Ledger with columns: finding_id, severity, fixer_decision, rationale/evidence, files_changed, follow_up, lesson_candidate. The ledger must label its state column `Fixer Decision` or `Fixer Proposal`, never `Decision` when this worker writes it.",
    "- Required fixer proposals: every BLOCKER/REQUIRED finding needs `FIX_PROPOSED`, `REBUTTAL_PROPOSED`, `OUTSIDE_OF_SCOPE`, `ACCEPT_REFRAME`, `REJECT_REFRAME`, or `BLOCKED_NEEDS_USER` with the required evidence. If any BLOCKER/REQUIRED finding lacks a complete proposal or is blocked, do not submit a review rerun. Whether a proposed fix is accepted is solely the next independent reviewer's decision.",
    "- After fixing a false-evidence or overclaim finding, search all touched docs and code comments for the old claim and related stronger wording. Fix or qualify every occurrence before review rerun.",
    "- In code-review recovery, the Review Finding Decision Queue scope guard overrides the Boy Scout rule and all general cleanup guidance.",
    "- If the review report includes WITH_NOTES, NON_BLOCKING, POLISH, or OUT_OF_SCOPE notes, do not silently ignore them. Evaluate and justify each note, and only edit files for notes whose decision is fixed or follow_up-with-immediate-action.",
    "- If review findings say phase artifacts are untracked, unstaged, uncommitted, or otherwise not durable, inspect the repository that owns those artifacts and either make a focused local commit for the relevant artifacts or revert the phase completion claim if durability cannot be made safely. Never push during this workflow.",
    "- After fixing code-review findings, add a concise narrative note that review fixes are ready for an independent rerun. Do not change status or gate-decision tokens; Hepha reruns review from the validated Fixer Response contract.",
  ];
}
