/** Defines a complete, immutable acceptance contract for actionable review findings. */
export function renderPhaseCodeReviewFindingContractRules() {
  return [
    "- On a code-review rerun, audit only the previous review findings against their recorded acceptance contracts, plus a direct regression demonstrably caused by their proposed fixes. Do not perform another exploratory sweep or introduce an unrelated new finding; the baseline review must state the complete contract before a fixer is dispatched.",
    "- Every BLOCKER/REQUIRED finding must include a measurable `Acceptance evidence required` statement: exact regression test(s), deterministic check, source/call audit, or other concrete evidence that proves the required invariant and its stated boundaries. Do not issue a finding that only says what to edit; define what post-fix behavior must be demonstrated.",
    "- Every BLOCKER/REQUIRED finding is a complete contract for the fixer, not a diagnosis. Its Required Change and Acceptance evidence must state: (1) exact in-scope production locations/behaviours, (2) every required invariant, (3) every forbidden case, (4) bounded/type constraints where relevant, (5) exact negative regression cases, and (6) at least one valid positive control. Do not use unresolved shorthand such as `complete the matrix`, `fully validate`, `handle all cases`, or `etc.`.",
    "- Before issuing a BLOCKER/REQUIRED finding that changes a field or parameter contract, complete the whole contract now: whether it is required or optional; the absent/null/type/format/bounds rules; all guards before use; every affected caller migration; forbidden fallbacks; exact negative cases; and a valid positive control. Do not split one field's contract across serial reviews (for example, required in one review, guard in the next, and content validation in a later review). A condition visible in the baseline review but absent from its first acceptance contract cannot be added to that finding on a rerun.",
    "- Every in-scope BLOCKER/REQUIRED finding must include the canonical `compatibilityDecision` field—the V1 Compatibility Decision—with `breaking_change_permitted` or `backward_compatibility_required`. The latter additionally requires non-empty canonical `compatibilityApprovalSource` (Compatibility approval source) and `compatibilityJustification` fields, naming an approved Feature/EPIC requirement or public deployed-contract obligation; a review finding, planning narrative, local caller, test, fixture, or development data is not such authority. Do not include approval source or justification for a breaking decision. State every production caller that must migrate and every forbidden fallback in the remediation instruction. Never leave compatibility to fixer inference.",
    "- For a finding about a discriminator, disposition, state, policy, or cross-field matrix, include an explicit Markdown `Acceptance Matrix` in the finding: one row per value/case with Required fields, Forbidden fields, permitted values/severity, and the expected manifest/result rule. A fixer must be able to implement all rows without inferring missing requirements from planning prose.",
    "- On a rerun, assess the fixer only against the prior finding's recorded Acceptance Contract. Do not reveal another condition that was already in the reviewed production surface but missing from that contract. Do not use a rerun to correct an incomplete reviewer analysis. Do not put concerns outside that contract or phase into the code-review manifest/report at all. If the approved phase contract itself is genuinely ambiguous or insufficient, report `BLOCKED_NEEDS_USER` with the exact planning ambiguity rather than inventing a broader implementation requirement.",
  ];
}
