/** Defines reviewer-only decisions for fixer proposals and stable finding identities. */
export function renderPhaseCodeReviewAdjudicationRules() {
  return [
    "- For each previous finding, state the fixer claim and one exact `Reviewer Decision` token: `FIX_ACCEPTED`, `REBUTTAL_ACCEPTED_DEFERRED`, `REBUTTAL_REJECTED`, `REFRAME_INTO_SCOPE`, `FINDING_OPEN`, `NOT_APPLICABLE`, or `BLOCKED_NEEDS_USER`. Do not use vague prose such as fixed, still open, accepted, rejected, or deferred without the token. State whether the response matches the requested change and the phase contract.",
    "- If the fixer submitted `REBUTTAL_PROPOSED`, evaluate its stated contract basis and measurable evidence before deciding. Accept it only when that evidence satisfies the original invariant or proves the finding does not apply; use `REBUTTAL_ACCEPTED_DEFERRED` and record the argument considered, reviewer rationale, explicit deferred risk/ownership, and why the phase may proceed. If it fails, use `REBUTTAL_REJECTED`, retain the same finding ID, explain precisely why the argument/evidence fails, repeat the remaining acceptance evidence, and require a `FIX_PROPOSED` code change. Do not turn a rejected rebuttal into a NEW finding or silently carry it into another rerun.",
    "- If the fixer submitted `OUTSIDE_OF_SCOPE`, perform the scope-arbitration review before evaluating code. Read the cited phase task, acceptance criteria, and Production Code Review Target. If the fixer is correct, use `NOT_APPLICABLE`, add a detailed entry to `MemoryBank/Overview/TechnicalDebts.md` (observed concern, out-of-scope basis, likely owner, decision needed), and do not keep this issue as a BLOCKER/REQUIRED finding. If and only if the requested change is demonstrably in this phase's approved scope, issue one `REFRAME_INTO_SCOPE` decision for the same ID. The reframe must cite the exact phase-owned task/acceptance/target, specify the complete bounded contract, forbidden cases, acceptance evidence, and explain why the fixer scope justification is incorrect. A reframe is permitted once only; never use it to introduce new scope or compensate for an incomplete initial review.",
    "- If the fixer submitted `ACCEPT_REFRAME`, review the implementation against the one recorded reframe contract only. Use normal `FIX_ACCEPTED` or `FINDING_OPEN` outcomes; do not add another requirement. If the fixer submitted `REJECT_REFRAME`, do not issue another reframe or leave the finding open. Record `NOT_APPLICABLE`, add the detailed TechnicalDebt entry, and preserve the fixer/reviewer justifications for later audit. This is a terminal developer scope decision for this review cycle.",
    "- A prior `FIX_ACCEPTED`, `NOT_APPLICABLE`, or `REBUTTAL_ACCEPTED_DEFERRED` finding ID is settled. Do not reuse it for a different defect, even in the same file. Use that same ID with `FINDING_OPEN` only when the current fix demonstrably regressed its accepted invariant, or when the reviewer identifies a specific acceptance condition from the original finding that the earlier decision failed to verify and that remains unmet. In the latter case, quote that original condition and explain why this is residual original scope; otherwise assign a distinct ID and explain why the concern was not in the prior finding.",
    "- A repeated finding ID may require only the outstanding acceptance evidence from its original finding. Do not silently broaden its required remediation to sibling validators, callers, or surfaces. A distinct finding is permitted only for a direct regression introduced by the current fixer change and only when it remains within this phase's approved production-code scope.",
    "- For human-readable presentation only, preferably put a concise comparison near the beginning of each previous-finding follow-up and open-finding summary: `Progress since predecessor: REDUCED|UNCHANGED|REGRESSED|RESOLVED. Accepted this cycle: <specific verified obligations or None>. Still outstanding: <specific residual obligations or None>.` Use `REDUCED` when at least one original obligation is now independently verified but another remains, `UNCHANGED` when no additional original obligation was verified, `REGRESSED` when a previously satisfied original obligation now fails, and `RESOLVED` when all original obligations are verified.",
    "- This progress wording is best-effort presentation text only. It is not a schema field, workflow state, gate input, acceptance prerequisite, or parser contract. Missing labels, different wording, an unrecognized progress word, reordered text, or imperfect formatting must never invalidate or repair an otherwise valid manifest, fail a phase, change the reviewer decision, or block a transition. Do not add progress fields to the V1 artifact schema and do not create a finding about presentation formatting.",
    "- `Repeated finding` is only a stable identity label. For reader clarity, do not use it by itself as the progress explanation or imply that the whole request is unchanged when the independently verified residual scope has reduced. Prefer putting the progress comparison first so bounded presentation reports retain what advanced and what remains.",
    "- Do not create `NEW`, `SCOPE_EXPANSION`, or `OUT_OF_SCOPE` findings in this bounded code-review manifest/report. `OUTSIDE_OF_SCOPE` is a fixer response state, not a reviewer finding. Do not use a missed broad application requirement, a future architecture concern, or a later-phase responsibility as a reason to expand a stable finding ID or to block this phase.",
    "- Do not report a previous finding as a new finding unless it is still open; in that case retain the same finding ID, mark it as repeated only after the progress comparison, and state the exact residual work.",
  ];
}
