import { LOGICAL_ACCEPTANCE_COVERAGE_CONTRACT } from "./logical-acceptance-coverage-contract.js";
import { PROJECT_TEST_PLAN_AUTHORING_POLICY } from "./project-test-plan-authoring-policy.js";
import { ACCEPTANCE_RESPONSIBILITY_POLICY } from "../../acceptance-responsibility-policy.js";
/** Shared across planning, implementation, independent review and readiness.
 * Project-owned obligations supply the technology and scope; this policy adds none. */
import { verificationSetupContract } from "./verification-setup-contract.js";
export const VERIFICATION_CONTRACT_VERSION = "collective-verification/v2";
export function verificationContract(includeAuthoring = false, authority: "verification" | "repair" = "verification"): string {
  return [
    `Shared verification contract (${VERIFICATION_CONTRACT_VERSION}):`,
    verificationSetupContract(),
    includeAuthoring ? PROJECT_TEST_PLAN_AUTHORING_POLICY : "Read FeatureDescription.md ## TestPlan and Phase ## Verification References for project-owned commands, working directories, preparation dependencies, source inputs, generated outputs and evidence locations. Do not infer commands from project type or silently waive freshness checks for declared outputs; unsupported executor semantics are a capability gap. " + (authority === "repair" ? "This explicit repair may correct project-owned commands and evidence mappings within the accepted phase scope; verify them against current configuration before execution." : "Inspection/execution agents stay read-only. Explicit Refresh may use HEPHA's validated command publication before the baseline; assessment-only calls report gaps without writes."),
    ACCEPTANCE_RESPONSIBILITY_POLICY,
    LOGICAL_ACCEPTANCE_COVERAGE_CONTRACT,
    "Read the accepted feature/EPIC requirements, owning phase, planning decisions, project instructions and relevant implementation before judging coverage. Follow shared steps, fixtures, hooks, helpers and paired server tests to their actual setup/actions/assertions; a thin delegating step is not a missing implementation by itself.",
    "Assess complementary evidence collectively. Several tests and reports may prove different aspects of one criterion; no individual test must prove its entire scope. Explain what each cited test proves, how their contracts connect, and the exact remaining unproved behaviour. Do not count disconnected tests as proof of a required integration boundary. Require real browser, integration, TwinTest, physical or other layers only when the accepted project contract requires them; do not invent a universal test stack or downgrade an explicitly required layer.",
    "Keep configuration, discovery, implementation review, execution and acceptance proof separate. File presence, test names, tags, --list output, a successful setup check or a review approval are not passing test execution. An unavailable report/environment or an unsupported discovery adapter does not establish missing tests. Follow documented delegation and existing setup before concluding implementation is absent.",
    "FeatureDescription.md is the entry point for the feature's test inventory: describe and list the owning repositories, test locations/identities, configured checks and obligation mappings, directly or through explicit links to shared project configuration and phase/planning matrices. When implementation adds, renames, moves, replaces or removes a test, update that inventory and its references in the same change. Readiness follows and validates this documented contract; it must not invent a different test plan on each Refresh. Missing or stale references are specific documentation/configuration gaps, not permission to drop required checks. " + (authority === "repair" ? "The authorized repair maintains this inventory alongside its test/configuration changes and records why each command changed." : "Inspection and execution agents do not rewrite the inventory; explicit Refresh uses the bounded host publication step before taking the execution baseline."),
    "Maintain detailed verification evidence in the linked phase/planning artifacts: criterion and observable obligations -> owning repository and exact test identities -> runner/configuration and selection filters -> setup/cleanup and authority -> report paths, tested source state and actual outcomes. Reuse existing project conventions; no HEPHA-specific test tags or one giant end-to-end test are required. Existing features without a linked inventory may reconstruct the mapping from authoritative current phase/configuration source, publishing the admitted inventory through explicit Refresh without regenerating tests; assessment-only actions merely report that gap.",
    "Before changing tests, inspect their history/rationale and shared callers, identify phase ownership and regression impact, and capture a meaningful failing check where executable. Repair the existing implementation rather than duplicating coverage or weakening assertions. Preserve test layers and full-suite gates required by the project. Choose focused checks plus regressions justified by changed dependencies; record why tests were selected or valid results reused, including zero selection, skips and failures.",
    "Reuse valid evidence and retain partial proof. When blocked, distinguish missing implementation, missing execution, unavailable environment, missing evidence linkage and insufficient information. Cite the inspected sources, remaining obligation and exact next action. Do not relabel the same unchanged blocker as a new successful repair.",
    "This checklist grants no additional authority. Bounded runner-owned setup and cleanup may run only within the existing action and project permissions. Do not leave services running, alter shared environments or provision external infrastructure without authority. If a discovered defect exceeds the current action, report it for a separate phase-scoped repair; do not silently expand the task.",
  ].join("\n");
}
