/** Configuration establishes dependencies; generated narratives are navigation only. */
export function verificationSetupContract(): string {
  return [
    "Current-source setup contract (verification-setup/v2): derive each required service, endpoint, credential, identity and state-control dependency from the selected runner configuration and its actual fixture/hooks/helper implementation. Cite the precise configuration/source path and the setting or call establishing each dependency. A planning report, previous receipt, recovery note, cached check reason, sibling directory or guessed conventional port cannot establish an infrastructure prerequisite. Repetition does not corroborate a claim.",
    "Follow each claimed dependency to current code before adding it to the plan or probing it. When historical documentation contradicts configuration, record the discrepancy and use the actual dependency graph; do not reproduce the historical blocker or invent a fixture owner. Distinguish a runner-owned service that is not started yet from an unavailable external dependency. Within existing authority, use the configured bounded test-owned setup and cleanup, including the runner's documented enablement flags. Do not require a runner-owned fixture to be running before invoking its setup. Do not provision unrelated services.",
    "Inspect scenario state arrangement as well as service startup: a Given step that only checks authentication does not create the server state described by its title. If state hooks or setup instructions are missing, identify those exact source gaps for phase repair. A removed false prerequisite does not prove the remaining setup or browser execution passes. Continue independent checks and retain actual failures; never substitute discovery for execution.",
    "For each selected aggregate script, read its delegated commands and reporter configuration. If it hides --no-build, forwards no reporter options, or produces only summary counts, select its underlying configured test projects/filters with source builds and native reports before execution. Preserve every required assertion and script-specific guard/cleanup; retain any additional guard as a separate supporting check when necessary. Do not merely rename a test as static to make missing evidence disappear. Do not append reporter arguments to a wrapper that ignores them. Native reports must come from the executed runners, never be reconstructed from console totals.",
  ].join("\n\n");
}
