import { executionReceiptExchange } from "../../manual-test-verification/execution-receipt-contract.js";
/** Execution and repair agents must produce the artifacts the readiness importer consumes. */
export function verificationExecutionContract(options: { directory?: string; runId?: string; rerunAll?: boolean; repair?: boolean; continueRepair?: boolean } = {}): string {
  return [
    "Execution completion contract: creating, discovering or reviewing tests is not the end of verification. Run the selected configured checks after any test/code repair and save their actual machine-reporter output before returning.",
    options.rerunAll ? "For this explicit Refresh rerun EVERY selected check, even if it passed previously and even if code is unchanged. Execute shared checks only once. Historical reports cannot certify this invocation."
      : "Reuse valid passing evidence for unchanged obligations; do not rerun unrelated passing suites.",
    "Use the repository's configured runner, working directory, filters and documented bounded setup/cleanup. First inspect shared fixtures and required authority. Never treat a prerequisite acknowledgement as availability. If setup, scope or authority is unavailable, stop with the exact unmet prerequisite, responsible project setup role and next action; do not retry the same blocker.",
    "Capture a machine-readable report with executed test identities and outcomes (Playwright/Vitest JSON, TRX, or supported Cargo test output), not just --list or a console success message. Configure reporter output for this run without altering test selection or assertions. Preserve failures, skips, zero selections, command, exit code and timestamps truthfully.",
    options.directory ? `Persist receipt.json and all reports inside ${options.directory}. Include audit.runId ${options.runId} for correlation when available; its absence alone does not block evidence validation. Record audit.testExecutionTimestamp only when the actual execution time is known; omit it if obtaining the timestamp fails. This audit field is optional and timestamp recording errors alone do not block valid evidence. Never guess or copy a timestamp. Account for every selected check ID exactly once with its planned cwd and command, including failed or blocked checks. Do not copy historical reports. If no checks legitimately apply, save an empty checks array; scope assessment must still verify applicability.`
      : "Persist a uniquely named JSON receipt under the FEATURE folder verification/. Preserve earlier receipts and reports.",
    "Use the exact verification.execution.receipt exchange schema below. HEPHA generates receipt-template.json and receipt-schema.json beside receipt-context.json for explicit Refresh. Copy the template identity fields (feature and each check id, kind, cwd and command) unchanged; fill only actual execution outcomes and native report bindings. Null outcome placeholders mean unknown, never passed, and must be replaced by truthful values or an unsuccessful result. Remove unused optional fields, including unavailable revision and report bindings on unsuccessful checks. Do not invent properties, rename fields or reconstruct the schema from historical receipts. Runtime schema and native evidence validation are mandatory.",
    executionReceiptExchange.renderContract(),
    "reportPath, extraReportPath and reports are exclusively native test-result reports. Build provenance, manifests and diagnostic JSON belong in artifacts:[{path,sha256}]; console logs belong in logPath/logSha256. Every attachment is checksum-validated, but supporting artifacts never count as tests or replace native test results. Do not put a provenance JSON file in extraReportPath.",
    "Classify static/preparation/discovery checks separately from tests. Their receipt requires a checksum-bound process log and truthful exit/success with tests:0,passed:0,failed:0; successful commands may produce an empty log. Discovery counts are not executed test counts. These checks never certify automated coverage. A custom script with only a console success message cannot be relabelled as a passing test: use its supported native reporter or report the evidence limitation.",
    options.repair === false ? "Verification-only authority: preserve failures and diagnose the next action; no automatic test/code correction is authorized."
      : options.continueRepair ? "For this explicit repair, continue focused corrections and rerun affected checks while evidence shows progress. Preserve every failed and passing outcome. Stop for scope/authority blockers, an architectural impasse or repeated unchanged failure; do not weaken assertions, skip tests, loosen configuration or change requirements merely to pass."
      : "When an executed check fails, inspect its failure and the accepted behaviour before editing. Within this phase's existing repair authority, make at most one focused correction attempt, rerun the failed configured checks and affected regressions, and save both outcomes. Do not weaken assertions, skip tests, loosen configuration or change requirements merely to pass. If the defect exceeds scope, setup is blocked, or the correction still fails, publish the exact remaining diagnosis and stop. No unbounded repair/reassessment loop.",
    "Return only after saving an executed result or a concrete blocked/failed diagnosis. The orchestrator independently reassesses evidence; an empty diagnosis, agent success message or created file cannot establish verification success.",
    "Use this current contract for receipt structure. Previous receipts are historical evidence, never schema definitions. HEPHA normally supplies runId as correlation metadata; missing runId alone cannot turn valid execution evidence into a failure.",
    'For a command producing multiple native reports, use reports:[{"path":"actual report path","sha256":"actual SHA-256"}, ...] instead of reportPath/extraReportPath. Include every executed suite, with aggregate counts matching their unique executed identities. Keep console output separately in logPath/logSha256. All reports must be captured in this invocation; a summary-only wrapper log cannot replace them. Do not mix the reports array with legacy reportPath/extraReportPath fields.',
    'testedRevision accepts a commit hash, "working tree @ <hash> (qualifications)", "<hash> @ working tree (qualifications)", or "<hash> + qualified working-tree edits". Both working tree and working-tree spellings are accepted. For one repository record one unambiguous hash. For a check spanning explicitly configured repositories, record each repository hash with its own working-tree qualification, separated by semicolons; put the execution cwd repository first and name each repository. HEPHA validates these against the configured source owners. Never describe a dirty tree as a clean commit or use alternative revisions joined by "or".',
    "A native stdout report may also be the checksum-bound logPath: the same file serves both roles but its tests count once. Never add that file again as another native report or another execution.",
    "Store the configured working directory in cwd and prefer the selected check's command in command. A literal cd to that same cwd followed by && is also accepted in command when the remaining invocation is equivalent. Literal POSIX/Bash single/double quoting, escaped spaces and separator whitespace may differ if decoded arguments and shell operators remain identical. Preserve the actual executed command for audit. Expansions and other unsupported syntax are not guessed to be equivalent. This presentation allowance does not authorize changes to test selection, runner options or report destinations.",
    "A test command may add one terminal > console.log redirection, optionally followed by 2>&1, when it captures a separate checksum-bound logPath inside this run directory. Preserve the planned literal arguments and operators before that suffix and its independent native report destination. Do not replace existing redirects, append to old logs, change filters, or add shell statements. Console capture is audit context, not test selection.",
  ].join("\n\n");
}
