import { verificationInventoryCommands } from "../../manual-test-verification/verification-inventory-contract.js";
/** One response contract for inspection and correction. The example is valid
 * JSON, but its placeholders are never executable configuration or evidence. */
export function verificationPlanOutputContract(phaseNumbers: readonly number[]) {
  const template = {
    checks: [{ id: "check-1", kind: "test", suiteKey: "<configured runner/environment profile>",
      cwd: "<absolute configured working directory>", command: "<configured command with run-local reporter output>",
      configurationFiles: ["<configuration path relative to cwd>"], testPaths: ["<configured test path relative to cwd>"],
      dependsOn: [], reason: "<feature assertions, source references, setup/cleanup, authority and limitations>", gates: ["tests"] }],
    inventoryReconciliation: { schemaVersion: "hepha-exchange/v1", kind: "verification.inventory.commands", payload: { replacements: [] } },
    phases: phaseNumbers.map(phaseNumber => ({ phaseNumber, checkIds: ["check-1"] })),
  };
  return [
    "Return exactly one complete JSON object, without explanation, Markdown fences, comments, alternatives or trailing commas.",
    `Verification plan JSON template:\n\`\`\`json\n${JSON.stringify(template, null, 2)}\n\`\`\``,
    "Replace every placeholder with inspected configuration; this is a shape example, not a command or a coverage claim. Add the required checks, replace example IDs consistently and map each phase to its actual checks. Preserve all required phases and deduplicate shared executions. Never execute or return placeholder commands.",
    "inventoryReconciliation describes command-only documentation corrections for HEPHA to apply before execution. Return its exact exchange schema below. Use replacements: [] when no existing command literal needs correction; HEPHA still publishes the inspected inventory and Phase references. For each correction, document is relative to the feature folder, checkId identifies an admitted check, before is the exact stale inline-code or shell-fence command in FeatureDescription.md ## TestPlan or a Phase ## Verification References section, after is exactly that check's command, and reason cites current configuration and why the required selection is preserved. Do not propose whole-document edits, criteria/flag/status changes, stale-result deletion, execution claims, or replacements outside these sections. Managed JSON inventory blocks are refreshed by HEPHA, not patched by the agent. If old commands live elsewhere, retain them as historical context and explain the superseding canonical selection in the check reason. Preserve IDs for unchanged checks. Reporter paths must use this invocation's configured output directory in the execution plan; HEPHA publishes a portable output-directory variable in the document.",
    verificationInventoryCommands.renderContract(),
    "cwd is the command working directory, not necessarily the repository owning its tests. All configurationFiles and testPaths stay relative to cwd. For a configured command delegating to another repository, include its actual runner/configuration in configurationFiles (for example ../service/run-tests.sh) and retain the matching testPaths (for example ../service/tests/*.spec.ts). Each external configuration must be a regular file in its own Git repository; test selections must stay inside the repositories bound by these configuration references. Explain the inspected delegation and feature scope in reason. Do not remove a linked runner reference or substitute local tests merely to avoid a cross-repository path. HEPHA snapshots every bound repository. Shared source files do not prove duplicate execution: distinct filters, assemblies, namespaces and configurations may share testPaths and suiteKey. Keep all selected source references. HEPHA rejects identical cwd/command executions; inspect actual delegated selections before deduplicating equivalent or containing executions.",
    "dependsOn optionally lists selected check IDs whose current artifacts/setup this check consumes. Derive it from inspected runner configuration, not previous availability claims. Include prerequisite checks and avoid cycles; HEPHA orders the handoff accordingly. kind is test, static, preparation or discovery. Only tests require nonempty testPaths and a suiteKey; only tests may declare gates (tests and/or gherkin_e2e) when the relationship is established. Omit gates otherwise. Static/preparation/discovery may have empty testPaths but must omit gates. For a genuinely non-automated phase, use checkIds: [] and add a nonempty noAutomationReason string explaining applicability. Missing tests or infrastructure are blockers, not reasons to omit required verification.",
  ].join("\n\n");
}
